/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.5
</auto-generated>
------------------------------------------------------------------------------ */

namespace Tests
{
    internal class TestAuthors
    {
        public const string SitefinityCLI = "Sitefinity CLI";
    }
}