/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.5
</auto-generated>
------------------------------------------------------------------------------ */

using MbUnit.Framework;

namespace Tests
{
    public class TestCategories
    {
        public const string Demo = "Demo";
    }
}